# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.extraModulePackages = [ ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "acpi_osi=!" "acpi_osi=\"Windows 2009\"" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6d6337fb-7d91-4d88-ab42-9b0a2dd5be8e";
    fsType = "btrfs";
    options = [ "compress=zlib" "discard" "noatime" "nodiratime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CE48-7CFE";
    fsType = "vfat";
    options = [ "discard" "noatime" "nodiratime" ];
  };

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = false;
  };
  hardware.bumblebee.enable = true;
  hardware.cpu.intel.updateMicrocode = true;
  hardware.pulseaudio.enable = true;

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/130bace6-c8ff-4a26-b842-4001b2829b33"; }
    ];
}
