# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
	imports = [
		<nixpkgs/nixos/modules/installer/scan/not-detected.nix>
	];

	# i915: enable better power savings
	# enable_guc_loading=1 and enable_guc_submission=1 are merged into enable_guc=3 since Linux 4.16+
	# update this when kernel changes to 4.16+
	boot.extraModprobeConfig = ''
		options i915 enable_dc=1 enable_fbc=1 enable_rc6=1 semaphores=1 disable_power_well=0 enable_guc_loading=1 enable_guc_submission=1
	'';
	boot.extraModulePackages = [ ];
	boot.initrd.availableKernelModules = [
		"ahci"
		"rtsx_pci_sdmmc"
		"sd_mod"
		"sr_mod"
		"usb_storage"
		"xhci_pci"
	];
	boot.kernelModules = [ "kvm-intel" ];
	boot.kernelParams = [
		"acpi_backlight=native" # best backlight control method for my computer
		"acpi_osi=!" # to make Nvidia play nice with Linux
		"acpi_osi=\"Windows 2009\"" # to make Nvidia play nice with Linux
		"intel_pstate=skylake_hwp" # this enables Intel's SpeedShift
	];

	fileSystems."/" = {
		device = "/dev/disk/by-uuid/6d6337fb-7d91-4d88-ab42-9b0a2dd5be8e";
		fsType = "btrfs";
		options = [ "compress=zlib" "discard" "noatime" "nodiratime" ];
	};
	fileSystems."/boot" = {
		device = "/dev/disk/by-uuid/CE48-7CFE";
		fsType = "vfat";
		options = [ "discard" "noatime" "nodiratime" ];
	};

	hardware.bluetooth = {
		enable = true;
		powerOnBoot = false;
	};
	hardware.bumblebee.enable = true;
	hardware.cpu.intel.updateMicrocode = true;
	hardware.pulseaudio.enable = true;

	nix.maxJobs = lib.mkDefault 8;
	powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

	swapDevices = [
		{ device = "/dev/disk/by-uuid/130bace6-c8ff-4a26-b842-4001b2829b33"; }
	];
}
